---
- name: Update all packages
  ansible.builtin.apt: #for debian based
    update_cache: yes
    upgrade: dist

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ additional_packages }}"
